### ISSUE TITLE
Fails to install on macOS Big Sur

### ISSUE THREAD

**Issue by kgpayne** [meltano/target-postgres#12]
> If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.

<img width="1434" alt="Screenshot 2022-02-04 at 11 44 23" src="https://user-images.githubusercontent.com/5585874/152523941-4488a048-c336-40f8-b217-847eeee8d0b8.png">

**Comment by tayloramurphy** [comment]
We are archiving this repository in favor of https://github.com/MeltanoLabs/target-postgres
