### ISSUE TITLE
Data missing when using a new Meltano SDK tap with child streams.

### ISSUE THREAD

**Issue by DanielPDWalker** [meltano/target-postgres#13]
I've been building a new SDK tap recently and have been testing it `target-postgres --variant meltano` and found that If you sync a tap with child streams the last results from the "last" child stream is the only data put into the database.

The Transferwise variant of `target-postgres` syncs all data from all child streams as expected.

Example:
- `StreamOne` gets 2 IDs for me, and I use `get_child_context` to set it up as a parent stream.
- `StreamTwo` sets `StreamOne` as it's parent stream, and uses the passed IDs in it's path.
- Using Transferwise `target-postgres` or `target-jsonl` I get 6 results back from `StreamTwo`.
- Using Meltano `target-postgres` I only get 1 result from `StreamTwo`, which is the number returned when using only the 2nd passed ID.

**Comment by E-Xor** [comment]
Yep, ran into it today.
Every child outputs SCHEMA message before multiple RECORD messages. Every encounter of SCHEMA makes target-postgres to reset array of records and thus doesn’t have anything to insert. A set of children for the last parent is the one that doesn’t have SCHEMA message after it thus being inserted by target-postgres. I tried target-jsonl and target-snowflake, they get all the children records properly.
https://github.com/meltano/target-postgres/blob/master/target_postgres/__init__.py#L139
Lines 139, 156, 164, 165

**Comment by tayloramurphy** [comment]
We are archiving this repository in favor of https://github.com/MeltanoLabs/target-postgres
