### ISSUE TITLE
Proposal: Archive repo

### ISSUE THREAD

**Issue by aaronsteers** [meltano/target-postgres#15]
@DouweM, @tayloramurphy, @WillDaSilva, @pnadolny13 

Can we archive this repo and remove from the hub?

We have another wip on MeltanoLabs with @visch contributing. And this doesn't have any updates in the past 2 years.

@DouweM - Cc'ing you in case you have historic knowlege.

**Comment by tayloramurphy** [comment]
@aaronsteers I'm in favor. I'll take it since I'll be moving the tap-salesforce one as well.

**Comment by tayloramurphy** [comment]
We are archiving this repository in favor of https://github.com/MeltanoLabs/target-postgres
